# Generated by Django 5.2 on 2025-08-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("blog", "博客文章"), ("comment", "评论")],
                        max_length=20,
                        verbose_name="内容类型",
                    ),
                ),
                ("content_id", models.PositiveIntegerField(verbose_name="内容ID")),
                ("original_content", models.TextField(verbose_name="原始内容")),
                (
                    "flag_by_AI",
                    models.BooleanField(default=False, verbose_name="是否由AI标记"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("reazon", models.TextField(blank=True, verbose_name="标记原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="复核时间"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "内容审核日志",
                "verbose_name_plural": "内容审核日志",
            },
        ),
    ]
