# Generated by Django 5.2.3 on 2025-06-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options_alter_blogcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.blog",
                verbose_name="所属博客",
            ),
        ),
    ]
