# Generated by Django 5.2 on 2025-08-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_moderationlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moderationlog",
            old_name="flag_by_AI",
            new_name="flagged_by_ai",
        ),
    ]
