# Generated by Django 5.2 on 2025-08-16 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_flag_by_ai_moderationlog_flagged_by_ai"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationlog",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布作者",
            ),
            preserve_default=False,
        ),
    ]
