# Generated by Django 5.2 on 2025-08-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_moderationlog_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationlog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.blogcategory",
                verbose_name="博客分类",
            ),
        ),
    ]
