# Generated by Django 5.2.3 on 2025-07-18 13:38

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogcomment_options_blogcomment_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcomment",
            options={"verbose_name": "博客评论", "verbose_name_plural": "博客评论"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="pub_time",
            field=models.DateTimeField(auto_now=True, verbose_name="发布时间"),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="blog.blogcomment",
                verbose_name="回复的评论",
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replyers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="回复的作者",
            ),
        ),
    ]
