# Generated by Django 5.2.3 on 2025-07-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogcomment_options_alter_blog_pub_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="content",
            field=models.TextField(max_length=20, verbose_name="内容"),
        ),
    ]
