# Generated by Django 5.2 on 2025-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_moderationlog_moderator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationlog",
            name="content_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="内容ID"
            ),
        ),
    ]
