# Generated by Django 5.2.3 on 2025-07-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogcomment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="content",
            field=models.TextField(max_length=200, verbose_name="内容"),
        ),
    ]
