# Generated by Django 5.2 on 2025-08-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_moderationlog_content_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["created_at"],
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
            },
        ),
    ]
