# Generated by Django 5.2 on 2025-08-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_notification_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moderationlog",
            options={
                "ordering": ["created_at"],
                "verbose_name": "内容审核日志",
                "verbose_name_plural": "内容审核日志",
            },
        ),
    ]
