# Generated by Django 5.2 on 2025-08-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_moderationlog_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moderationlog",
            old_name="reazon",
            new_name="reason",
        ),
    ]
