# Generated by Django 5.2.3 on 2025-07-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
            },
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
