# Generated by Django 5.2.3 on 2025-07-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=50, verbose_name="标题"),
        ),
    ]
