# Generated by Django 5.2 on 2025-08-26 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_reazon_moderationlog_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moderationlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "内容审核日志",
                "verbose_name_plural": "内容审核日志",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
            },
        ),
        migrations.AddField(
            model_name="moderationlog",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="举报者",
            ),
        ),
        migrations.AlterField(
            model_name="moderationlog",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderated_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人员",
            ),
        ),
    ]
