# Generated by Django 5.2 on 2025-09-09 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_moderationlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="修改时间",
            ),
            preserve_default=False,
        ),
    ]
