# Generated by Django 5.2.3 on 2025-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, verbose_name="标题"),
        ),
    ]
