# Generated by Django 5.2.3 on 2025-08-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_blog_view_count_alter_blog_title_bloglike"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
    ]
