# Generated by Django 5.2.3 on 2025-08-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_blog_like_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "博客分类",
                "verbose_name_plural": "博客分类",
            },
        ),
    ]
