# Generated by Django 5.2.3 on 2025-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qxauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="eamil",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
