# Generated by Django 5.2.3 on 2025-06-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qxauth", "0002_alter_captchamodel_eamil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="captchamodel",
            old_name="eamil",
            new_name="email",
        ),
    ]
