# Generated by Django 5.2.3 on 2025-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qxauth", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
