# Generated by Django 5.2.3 on 2025-06-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qxauth", "0006_profile_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
