# Generated by Django 5.2.3 on 2025-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qxauth", "0007_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
