# Generated by Django 5.2.3 on 2025-07-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qxauth", "0008_alter_profile_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaptchaModel",
        ),
    ]
